- hosts: localhost

  pre_tasks:
    - name: Assert Homebrew Is Installed
      stat: { path: /opt/homebrew/bin/brew }
      register: homebrew_installed

  tasks:
    - name: Determine who I am
      ansible.builtin.shell: "whoami"
      register: whoami

    - include_tasks: tasks/git.yml
    - include_tasks: tasks/homebrew.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/mac-apps.yml
    - include_tasks: tasks/node.yml

    # Personal
    - include_tasks: tasks/personal/all.yml
      when: ansible_hostname == "Ford" or ansible_hostname == "Ark"
    - include_tasks: tasks/ark/all.yml
      when: ansible_hostname == "Ark"
