- name: Tap Homebrew Fonts Cask
  homebrew_tap:
    name: "homebrew/cask-fonts"

- name: Install fonts from Homebrew
  homebrew_cask:
    name:
      - font-cascadia-code-pl
      - font-recursive-code
    state: latest
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name:
      - iterm2
      - raycast
      - slack
      - visual-studio-code
      - alt-tab
      - kaleidoscope
      - textexpander
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Install evergreen Homebrew
  homebrew:
    name:
      - git
      - gh
      - jesseduffield/lazygit/lazygit
    state: latest
    update_homebrew: true
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name:
      - mas
      - neovim
      - starship
      - wget
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists
