- name: Tap Homebrew Fonts Cask
  homebrew_tap:
    name: "homebrew/cask-fonts"

- name: Tap Homebrew Versions Cask
  homebrew_tap:
    name: "homebrew/cask-versions"

- name: Install fonts from Homebrew
  homebrew_cask:
    name:
      - font-cascadia-code-pl
      - font-recursive-code
      - font-fantasque-sans-mono
    state: latest
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name:
      # - iterm2
      - raycast
      - visual-studio-code-insiders
      - warp
      - elgato-stream-deck
      - setapp
      # - kaleidoscope
      - spotify
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Install evergreen Homebrew
  homebrew:
    name:
      - git
      - gh
      - jesseduffield/lazygit/lazygit
    state: latest
    update_homebrew: true
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name:
      - mas
      # - neovim
      # - starship
      - wget
      # - asdf
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists
