- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name:
      - google-chrome
      - iterm2
      - raycast
      - slack
      - visual-studio-code
      - alt-tab
      - kaleidoscope
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists

- name: Installing Homebrew Packages
  homebrew:
    name:
      - git
      - mas
      - neovim
      - starship
      - wget
      - gh
    state: present
    update_homebrew: true
  register: result
  until: result is successful
  when: homebrew_installed.stat.exists
